// Video Data

let videos = [
	{
		index: 0,
		likesCount: "455K",
		videoPreview: "img/video-previews/iphone_14_pro.jpg",
		channelLogo: "img/channel-logo/apple.jpg",
		videoTitle: "Introducing iPhone 14 Pro | Apple",
		iframe: "https://www.youtube.com/embed/FT3ODSg1GFE",
		channeName: "Apple",
		channelSubs: "16.2M",
		videoViews: "15M views",
		videoViewsEx: '15,295,235',
		videoDate: "3 days ago",
		videoDuration: "4:19",
		channelVerification: "check_circle"
	},
	{
		index: 1,
		likesCount: "337K",
		videoPreview: "img/video-previews/expert.jpg",
		channelLogo: "img/channel-logo/veritasium.jpg",
		videoTitle: "The 4 things it takes to be an expert",
		iframe: "https://www.youtube.com/embed/5eW6Eagr9XA",
		channeName: "Veritasium",
		channelSubs: "12.8M",
		videoViews: "6M views",
		videoViewsEx: '6,340,560',
		videoDate: "1 months ago",
		videoDuration: "17:58",
		channelVerification: "check_circle"
	},
	{
		index: 2,
		likesCount: "35K",
		videoPreview: "img/video-previews/cesca.jpg",
		channelLogo: "img/channel-logo/vox.jpg",
		videoTitle: "Why everyone has this chair",
		iframe: "https://www.youtube.com/embed/0V2qtmV2JGE",
		channeName: "Vox",
		channelSubs: "10.8M",
		videoViews: "1.1M views",
		videoViewsEx: '1,180,320',
		videoDate: "5 months ago",
		videoDuration: "6:02",
		channelVerification: "check_circle"
	},
	{
		index: 3,
		likesCount: "246K",
		videoPreview: "img/video-previews/space_straw.jpg",
		channelLogo: "img/channel-logo/vsauce.jpg",
		videoTitle: "SPACE STRAW",
		iframe: "https://www.youtube.com/embed/im7DzMr8Ygs",
		channeName: "Vsauce",
		channelSubs: "18M",
		videoViews: "11M views",
		videoViewsEx: '11,244,330',
		videoDate: "9 years ago",
		videoDuration: "10:13",
		channelVerification: "check_circle"
	},
	{
		index: 4,
		likesCount: "472K",
		videoPreview: "img/video-previews/cycle.jpg",
		channelLogo: "img/channel-logo/smarter_everyday.jpg",
		videoTitle: "The Backwards Brain Bicycle - Smarter Every Day 133",
		iframe: "https://www.youtube.com/embed/MFzDaBzBlL0",
		channeName: "SmarterEveryDay",
		channelSubs: "10.5M",
		videoViews: "29M views",
		videoViewsEx: '29,232,130',
		videoDate: "7 years ago",
		videoDuration: "7:58",
		channelVerification: "check_circle"
	},
	{
		index: 5,
		likesCount: "279K",
		videoPreview: "img/video-previews/japan_train_first_class.jpg",
		channelLogo: "img/channel-logo/solo_solo_travel.jpg",
		videoTitle: "Riding on Japan’s First Class Overnight Train",
		iframe: "https://www.youtube.com/embed/tBdwetBS1DA",
		channeName: "Solo Solo Travel",
		channelSubs: "676K",
		videoViews: "20M views",
		videoViewsEx: '20,232,130',
		videoDate: "3 months ago",
		videoDuration: "17:44",
		channelVerification: ""
	},
	{
		index: 6,
		likesCount: "113K",
		videoPreview: "img/video-previews/notes_on_ipad.jpg",
		channelLogo: "img/channel-logo/ali_abdaal.jpg",
		videoTitle: "How I take notes on my iPad Pro in medical school",
		iframe: "https://www.youtube.com/embed/waR3xBDHMqw",
		channeName: "Ali Abdaal",
		channelSubs: "3.1M",
		videoViews: "5.9M views",
		videoViewsEx: '5,932,130',
		videoDate: "4 years ago",
		videoDuration: "13:56",
		channelVerification: ""
	},
	{
		index: 7,
		likesCount: "90K",
		videoPreview: "img/video-previews/viola.jpg",
		channelLogo: "img/channel-logo/the_new_york_times.jpg",
		videoTitle: "This Is What a $45 Million Viola Sounds Like",
		iframe: "https://www.youtube.com/embed/Xe11Pp1g39I",
		channeName: "The New York Times",
		channelSubs: "4.15M",
		videoViews: "5.6M views",
		videoViewsEx: '5,632,130',
		videoDate: "8 years ago",
		videoDuration: "3:24",
		channelVerification: "check_circle"
	},
	{
		index: 8,
		likesCount: "820K",
		videoPreview: "img/video-previews/cicada_3301.jpg",
		channelLogo: "img/channel-logo/lemmino.jpg",
		videoTitle: "Cicada 3301: An Internet Mystery",
		iframe: "https://www.youtube.com/embed/I2O7blSSzpI",
		channeName: "LEMMINO",
		channelSubs: "4.85M",
		videoViews: "29M views",
		videoViewsEx: '29,232,130',
		videoDate: "4 years ago",
		videoDuration: "17:54",
		channelVerification: "check_circle"
	},
	{
		index: 9,
		likesCount: "16K",
		videoPreview: "img/video-previews/google_ceo.jpg",
		channelLogo: "img/channel-logo/nothing_but_tech.jpg",
		videoTitle: "Talking Tech With Google CEO Sundar Pichai!!",
		iframe: "https://www.youtube.com/embed/4hEDKbUk03k",
		channeName: "NothingButTech",
		channelSubs: "1.3M",
		videoViews: "180K views",
		videoViewsEx: '180,130',
		videoDate: "3 months ago",
		videoDuration: "9:41",
		channelVerification: ""
	},
	{
		index: 10,
		likesCount: "10K",
		videoPreview: "img/video-previews/google_maps.jpg",
		channelLogo: "img/channel-logo/wall_street_journal.jpg",
		videoTitle: "How Google Remapped the World | The Tech Behind",
		iframe: "https://www.youtube.com/embed/oOAzFIeMBcg",
		channeName: "Wall Street Journal",
		channelSubs: "3.78M",
		videoViews: "700K views",
		videoViewsEx: '700,210',
		videoDate: "5 days ago",
		videoDuration: "8:42",
		channelVerification: ""
	},
	{
		index: 11,
		likesCount: "21K",
		videoPreview: "img/video-previews/blackrock.jpg",
		channelLogo: "img/channel-logo/cnbc.jpg",
		videoTitle: "How BlackRock Became The World's Largest Asset Manager",
		iframe: "https://www.youtube.com/embed/ga_we_sOopk",
		channeName: "CNBC",
		channelSubs: "3.0M",
		videoViews: "1.4M views",
		videoViewsEx: '1,432,130',
		videoDate: "10 months ago",
		videoDuration: "14:19",
		channelVerification: "check_circle"
	},
	{
		index: 12,
		likesCount: "59K",
		videoPreview: "img/video-previews/hamming_codes.jpg",
		channelLogo: "img/channel-logo/3blue1brown.jpg",
		videoTitle: "How to send a self-correcting message (Hamming codes)",
		iframe: "https://www.youtube.com/embed/X8jsijhllIA",
		channeName: "3Blue1Brown",
		channelSubs: "4.69M",
		videoViews: "1.6M views",
		videoViewsEx: '3,232,130',
		videoDate: "1 year ago",
		videoDuration: "20:05",
		channelVerification: ""
	},
	{
		index: 13,
		likesCount: "75K",
		videoPreview: "img/video-previews/china_keyboard.jpg",
		channelLogo: "img/channel-logo/johnny_harris.jpg",
		videoTitle: "How China Conquered The Keyboard",
		iframe: "https://www.youtube.com/embed/hBDwXipHykQ",
		channeName: "Johnny Harris",
		channelSubs: "2.92M",
		videoViews: "2M views",
		videoViewsEx: '2,335,120',
		videoDate: "1 year ago",
		videoDuration: "21:06",
		channelVerification: "check_circle"
	},
	{
		index: 14,
		likesCount: "199K",
		videoPreview: "img/video-previews/marques_sundar.jpg",
		channelLogo: "img/channel-logo/marques-brownlee.jpg",
		videoTitle: "Talking Tech and AI with Google CEO Sundar Pichai!",
		iframe: "https://www.youtube.com/embed/n2RNcPRtAiY",
		channeName: "Marques Brownlee",
		channelSubs: "16.2M",
		videoViews: "4M views",
		videoViewsEx: '4,232,130',
		videoDate: "1 year ago",
		videoDuration: "14:21",
		channelVerification: "check_circle"
	},
	{
		index: 15,
		likesCount: "4.6K",
		videoPreview: "img/video-previews/real_estate.jpg",
		channelLogo: "img/channel-logo/bedimcode.jpg",
		videoTitle: "Responsive Real State Website | HTML CSS & JavaScript",
		iframe: "https://www.youtube.com/embed/twRLgPsP1H0",
		channeName: "Bedimcode",
		channelSubs: "120K",
		videoViews: "125K views",
		videoViewsEx: '125,876',
		videoDate: "4 months ago",
		videoDuration: "2:38:26",
		channelVerification: ""
	}
];


let videosPage = [
	{
		index: 0,
		videoPreview: "img/video-previews/airpods_max.jpg",
		channelLogo: "img/channel-logo/marques-brownlee.jpg",
		videoTitle: "AirPods Max Unboxing & Impressions: $550?!",
		iframe: "https://www.youtube.com/embed/UdfSrJvqY_E",
		channeName: "Marques Brownlee",
		channelSubs: "12M",
		videoViews: "12M views",
		videoViewsEx: '12,129,945',
		videoDate: "1 year ago",
		videoDuration: "11:52",
		channelVerification: "check_circle"
	},
	{
		index: 1,
		videoPreview: "img/video-previews/bike_veritasium.jpg",
		channelLogo: "img/channel-logo/veritasium.jpg",
		videoTitle: "Most People Don't Know How Bikes Work",
		iframe: "https://www.youtube.com/embed/daaDuC1kbds",
		channeName: "Veritasium",
		channelSubs: "13M",
		videoViews: "18M views",
		videoViewsEx: '18,340,560',
		videoDate: "9 monthss ago",
		videoDuration: "11:22",
		channelVerification: "check_circle"
	},
	{
		index: 2,
		videoPreview: "img/video-previews/how_does_the_internet_work.jpg",
		channelLogo: "img/channel-logo/vox.jpg",
		videoTitle: "How Does the Internet Work? - Glad You Asked S1",
		iframe: "https://www.youtube.com/embed/NTHVTY6w2Co",
		channeName: "Vox",
		channelSubs: "11.2M",
		videoViews: "26M views",
		videoViewsEx: '26,680,320',
		videoDate: "2 years ago",
		videoDuration: "19:54",
		channelVerification: "check_circle"
	},
	{
		index: 3,
		videoPreview: "img/video-previews/illutions_of_time.jpg",
		channelLogo: "img/channel-logo/vsauce.jpg",
		videoTitle: "Illusions of Time",
		iframe: "https://www.youtube.com/embed/NTHVTY6w2Co",
		channeName: "Vsauce",
		channelSubs: "26M",
		videoViews: "14M views",
		videoViewsEx: '14,244,330',
		videoDate: "1 years ago",
		videoDuration: "31:08",
		channelVerification: "check_circle"
	},
	{
		index: 4,
		videoPreview: "img/video-previews/how_films_work.jpg",
		channelLogo: "img/channel-logo/smarter_everyday.jpg",
		videoTitle: "How Does Film ACTUALLY Work? (It's MAGIC)",
		iframe: "https://www.youtube.com/embed/NTHVTY6w2Co",
		channeName: "SmarterEveryDay",
		channelSubs: "902K",
		videoViews: "3.3M views",
		videoViewsEx: '3,232,130',
		videoDate: "1 years ago",
		videoDuration: "31:08",
		channelVerification: "check_circle"
	},
	{
		index: 5,
		videoPreview: "img/video-previews/japan_train.jpg",
		channelLogo: "img/channel-logo/solo_solo_travel.jpg",
		videoTitle: "Riding Japan's Incredible Machine Train",
		iframe: "https://www.youtube.com/embed/NTHVTY6w2Co",
		channeName: "Solo Solo Travel",
		channelSubs: "425K",
		videoViews: "3M views",
		videoViewsEx: '3,232,130',
		videoDate: "6 months ago",
		videoDuration: "16:35",
		channelVerification: ""
	},
	{
		index: 6,
		videoPreview: "img/video-previews/cheap_purchases.jpg",
		channelLogo: "img/channel-logo/ali_abdaal.jpg",
		videoTitle: "10 cheap purchases that improved my life",
		iframe: "https://www.youtube.com/embed/NTHVTY6w2Co",
		channeName: "Ali Abdaal",
		channelSubs: "6M",
		videoViews: "1.3M views",
		videoViewsEx: '3,232,130',
		videoDate: "1 months ago",
		videoDuration: "9:08",
		channelVerification: ""
	},
	{
		index: 7,
		videoPreview: "img/video-previews/liberal_hypocrisy.jpg",
		channelLogo: "img/channel-logo/the_new_york_times.jpg",
		videoTitle: "Liberal Hypocrisy is Fueling American Inequality. Here’s How.",
		iframe: "https://www.youtube.com/embed/NTHVTY6w2Co",
		channeName: "The New York Times",
		channelSubs: "8M",
		videoViews: "7.7M views",
		videoViewsEx: '3,232,130',
		videoDate: "9 months ago",
		videoDuration: "14:21",
		channelVerification: "check_circle"
	}
]
